import { shellQuote } from "@atelier/core";

const listenHost = "127.0.0.1";
const listenPort = 58124;
export const workspaceLocalProxyUrl = `http://${listenHost}:${listenPort}`;
const configPath = "/run/atelier-proxy/tinyproxy.conf";
const logPath = "/.atelier/egress-proxy.log";

type UpstreamProxy = { host: string; port: number; username: string; password: string };

export function workspaceLocalProxyConfig(upstream: UpstreamProxy) {
  // Workspace IDs/tokens and the bridge address are generated by Atelier, not
  // arbitrary user input. No domain-specific bypass rules: every request must
  // reach the authenticated host proxy, including ordinary HTTP requests.
  return `Listen ${listenHost}
Port ${listenPort}
Timeout 600
MaxClients 256
LogLevel Warning
DisableViaHeader Yes
Upstream http ${upstream.username}:${upstream.password}@${upstream.host}:${upstream.port}
`;
}

export function workspaceLocalProxyInitScript(upstream: UpstreamProxy): string {
  const config = workspaceLocalProxyConfig(upstream);
  return `install -d -m 700 /run/atelier-proxy
(umask 077; printf '%s\\n' ${shellQuote(config)} > ${configPath})
# The workspace-specific executable avoids host AppArmor rules for the
# distribution system service at /usr/bin/tinyproxy.
nohup /usr/local/bin/atelier-egress-proxy -d -c ${configPath} > ${logPath} 2>&1 < /dev/null &
proxy_pid=$!
proxy_listening() { ss -H -ltnp 'sport = :${listenPort}' | grep -Fq "pid=$proxy_pid,"; }
for _ in $(seq 1 100); do
  if ! kill -0 "$proxy_pid" 2>/dev/null || proxy_listening; then break; fi
  sleep .1
done
if ! kill -0 "$proxy_pid" 2>/dev/null || ! proxy_listening; then
  cat ${logPath} >&2
  echo 'Workspace egress forwarder did not start' >&2
  exit 1
fi`;
}
