export {
  AtelierCoreError,
  invalidArguments,
  type AtelierError,
} from "./errors.ts";

export {
  addManagedRepo,
  defaultDataDir,
  listManagedRepos,
  managedReposDir,
  type AddManagedRepoResult,
  type ManagedRepoListResult,
  type ManagedRepoSummary,
} from "./managed-repo.ts";

export {
  cloneManagedRepoIntoWorkspace,
  createWorkspace,
  createWorkspaceTerminal,
  deleteWorkspace,
  deleteWorkspaceTerminal,
  execWorkspace,
  execWorkspaceCommand,
  execWorkspaceShell,
  inspectWorkspaceDeleteSafety,
  getWorkspaceRepoMergeability,
  listWorkspaceTerminals,
  listWorkspaces,
  listWorkspaceRepos,
  pushWorkspaceRepo,
  setWorkspaceTitle,
  workspaceCommand,
  type DeleteWorkspaceOptions,
  type WorkspaceCloneResult,
  type WorkspaceCommandOptions,
  type WorkspaceDeleteBlockedDetails,
  type WorkspaceDeleteSafetyIssue,
  type WorkspaceExecResult,
  type WorkspaceListResult,
  type WorkspaceNewResult,
  type WorkspaceRepoListResult,
  type WorkspaceRepoMergeabilityResult,
  type WorkspaceRepoPushResult,
  type WorkspaceRepoWorkingTreeStatus,
  type WorkspaceTerminalCreateResult,
  type WorkspaceTerminalListResult,
} from "./workspace.ts";
