import type { JsonObject } from "@atelier/core";
const workspaceId = { name: "id", in: "path", required: true, schema: { type: "string" } };
const agentConversation = { name: "agent", in: "query", schema: { type: "string" } };
const errorResponse = { description: "Not found" };
const htmlSurfaceResponses = (description: string) => ({ "200": { description, content: { "text/html": { schema: { type: "string" } } } } });
const jsonAndHtmlResponse = (description: string, schema: JsonObject) => ({ "200": { description, content: { "application/json": { schema }, "text/html": { schema: { type: "string" } } } } });
export const subagentsOpenApiPaths = {
"/workspaces/{id}/subagents": { get: { summary: "Inspect a selected agent's subagent tree and plaintext communication ledger", parameters: [workspaceId, agentConversation, { name: "open", in: "query", required: false, schema: { type: "array", items: { type: "string" } } }, { name: "reveal", in: "query", required: false, schema: { type: "string" } }], responses: jsonAndHtmlResponse("Delegated agents, lifecycle states, messages and results; HTML contains folding child transcript frames", { type: "object", required: ["parent", "agents", "messages"], properties: { parent: { type: "object", required: ["id", "title"], properties: { id: { type: "string" }, title: { type: "string" } } }, agents: { type: "array", items: { type: "object" } }, messages: { type: "array", items: { type: "object" } } } }) } },
"/workspaces/{id}/subagents/{subagentId}/transcript": { get: { summary: "Render a child transcript in the selected root tree", parameters: [workspaceId, agentConversation, { name: "subagentId", in: "path", required: true, schema: { type: "string" } }, { name: "message", in: "query", required: false, schema: { type: "string" } }], responses: htmlSurfaceResponses("Server-rendered child transcript; message reveals its correlated tool call or final answer") } },
"/workspaces/{id}/subagents/reveal": { get: { summary: "Navigate to a message source or recipient", parameters: [workspaceId, { name: "child", in: "query", required: true, schema: { type: "string" } }, { name: "message", in: "query", required: true, schema: { type: "string" } }], responses: { "303": { description: "Redirect to the root transcript or expanded child" }, "404": errorResponse } }, post: { summary: "Reveal a message source or destination in its root or subagent transcript", parameters: [workspaceId], requestBody: { required: true, content: { "application/x-www-form-urlencoded": { schema: { type: "object", required: ["child", "message"], properties: { child: { type: "string" }, message: { type: "string" } } } } } }, responses: { "303": { description: "Redirect to the root transcript or an expanded child" }, "404": errorResponse } } },
} satisfies Record<string, JsonObject>;
