export {
  agentClientModule,
  agentClientModule as atelierClientModule,
  createAgentAttachmentsController,
  createAgentAutosubmitController,
  createAgentCopyController,
  createAgentElapsedController,
  createAgentNoticeController,
  createAgentPaneController,
  createAgentProxyController,
  createAgentTermController,
  registerAgentStreamActions,
  startAgentTab,
  type AgentPaneControllerInstance,
} from "./agent-controllers.ts";
